I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/TO_LIVE_SCRIPT/ERA ONE/1937 DAY ONE[7-9-37]/_1937_sino_japanese_war_bookmark.rpy", line 874, in script
    if fang.haslog("Hometown:Taiwan"):
  File "game/TO_LIVE_SCRIPT/ERA ONE/1937 DAY ONE[7-9-37]/_1937_sino_japanese_war_bookmark.rpy", line 874, in <module>
    if fang.haslog("Hometown:Taiwan"):
AttributeError: 'Char' object has no attribute 'haslog'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/TO_LIVE_SCRIPT/ERA ONE/1937 DAY ONE[7-9-37]/_1937_sino_japanese_war_bookmark.rpy", line 874, in script
    if fang.haslog("Hometown:Taiwan"):
  File "E:\renpy\renpy-6.99.12.4-sdk\renpy\ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "E:\renpy\renpy-6.99.12.4-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "E:\renpy\renpy-6.99.12.4-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/TO_LIVE_SCRIPT/ERA ONE/1937 DAY ONE[7-9-37]/_1937_sino_japanese_war_bookmark.rpy", line 874, in <module>
    if fang.haslog("Hometown:Taiwan"):
AttributeError: 'Char' object has no attribute 'haslog'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
To Live 0.0.6
Mon Jun 29 16:55:08 2020
